version: "3.3"

services:
  db:
    container_name: ${PROJECT_NAME:-wordpress}-db
    image: mariadb:10.5.8
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${DB_NAME:-wordpress}
      - MYSQL_USER=${DB_USER:-admin}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}

  wordpress:
    container_name: ${PROJECT_NAME:-wordpress}-wordpress
    image: wordpress:php8.2-apache
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${WP_PORT:-80}:80"
    volumes:
      - ./:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${DB_USER:-admin}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD:-password}
      - WORDPRESS_DB_NAME=${DB_NAME:-wordpress}
      - WORDPRESS_DEBUG=${WORDPRESS_DEBUG:-true}
      - WP_MEMORY_LIMIT=${WP_MEMORY_LIMIT:-256M}

  phpmyadmin:
    container_name: ${PROJECT_NAME:-wordpress}-phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${PMA_PORT:-8080}:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=${DB_USER:-admin}
      - PMA_PASSWORD=${DB_PASSWORD:-password}

  cli:
    container_name: ${PROJECT_NAME:-wordpress}-cli
    image: wordpress:cli-php8.2
    restart: on-failure
    depends_on:
      - db
      - wordpress
    volumes_from:
      - wordpress
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${DB_USER:-admin}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD:-password}
      - WORDPRESS_DB_NAME=${DB_NAME:-wordpress}
    command: tail -f /dev/null
    user: "33:33"

volumes:
  db_data:
    name: ${PROJECT_NAME:-wordpress}_db_data