version: "3.3"

x-wordpress_db: &wordpress_db
                  wordpress-cms
x-standardized_admin: &standardized_admin
                        admin
x-standardized_password: &standardized_password
                           password

x-env: &env
  environment:
    MYSQL_ROOT_PASSWORD: *standardized_password
    MYSQL_DATABASE: *wordpress_db
    MYSQL_USER: *standardized_admin
    MYSQL_PASSWORD: *standardized_password

    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_USER: *standardized_admin
    WORDPRESS_DB_PASSWORD: *standardized_password
    WORDPRESS_DB_NAME: *wordpress_db
    WORDPRESS_DEBUG: ${WORDPRESS_DEBUG-true}

    PMA_HOST: db
    PMA_USER: *standardized_admin
    PMA_PASSWORD: *standardized_password

    DOCKER: true

services:
  db:
    <<: *env
    image: mariadb:10.5.8
    restart: 'no'

  wordpress:
    <<: *env
    image: wordpress:php8.2-apache
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - './:/var/www/html'

  phpmyadmin:
    <<: *env
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80

  wordpress-cli:
    <<: *env
    image: wordpress:cli-php8.2
    depends_on:
      - db
      - wordpress
    links:
      - db:mysql
    command: tail -F anything
    volumes_from:
      - wordpress
    user: "33:33"